// Generated by lsc from core.ts

function JSFloorDiv(a: int, b: int): int
  requires b != 0
{
  if b > 0 then
    if a >= 0 then a / b
    else -((-a - 1) / b) - 1
  else
    if a <= 0 then (-a) / (-b)
    else -((a - 1) / (-b)) - 1
}

datatype Op = Add | Sub | Mul | Div | Lt | Eq

datatype Expr = Num(n: int) | Bool(b: bool) | Var(x: string) | Let(x: string, rhs: Expr, body: Expr) | Bin(op: Op, l: Expr, r: Expr) | If(cond: Expr, thn: Expr, els: Expr)

datatype Value = VNum(n: int) | VBool(b: bool)

datatype Fault = DivByZero | Unbound | TypeError | Underflow

datatype Result = Ok(v: Value) | Err(why: Fault)

datatype Binding = Binding(x: string, v: Value)

type Env = seq<Binding>

datatype Ty = TInt | TBool

datatype TBinding = TBinding(x: string, t: Ty)

type TEnv = seq<TBinding>

datatype TyResult = Typed(t: Ty) | IllTyped(why: Fault)

datatype Instr = Push(v: Value) | Prim(op: Op) | Load(x: string) | Bind(x: string) | Unbind | Branch(thn: seq<Instr>, els: seq<Instr>)

type Stack = seq<Value>

datatype Outcome = Halt(stack: seq<Value>, env: seq<Binding>) | Crash(why: Fault)

function size(e: Expr): int
  decreases e
{
  match e {
    case Num(i_e_n) =>
      1
    case Bool(i_e_b) =>
      1
    case Var(i_e_x) =>
      1
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      ((1 + size(i_e_rhs)) + size(i_e_body))
    case Bin(i_e_op, i_e_l, i_e_r) =>
      ((1 + size(i_e_l)) + size(i_e_r))
    case If(i_e_cond, i_e_thn, i_e_els) =>
      (((1 + size(i_e_cond)) + size(i_e_thn)) + size(i_e_els))
  }
}

lemma size_ensures(e: Expr)
  ensures (size(e) >= 1)
{
}

function lookup(env: seq<Binding>, x: string): Result
  decreases env
{
  if (|env| == 0) then
    Err(Fault.Unbound)
  else
    if (env[0].x == x) then
      Ok(env[0].v)
    else
      lookup(env[1..], x)
}

function applyOp(op: Op, a: Value, b: Value): Result
{
  if (a.VNum? && b.VNum?) then
    if op.Add? then
      Ok(VNum((a.n + b.n)))
    else
      if op.Sub? then
        Ok(VNum((a.n - b.n)))
      else
        if op.Mul? then
          Ok(VNum((a.n * b.n)))
        else
          if op.Div? then
            if (b.n == 0) then
              Err(Fault.DivByZero)
            else
              Ok(VNum(JSFloorDiv(a.n, b.n)))
          else
            if op.Lt? then
              Ok(VBool((a.n < b.n)))
            else
              Ok(VBool((a.n == b.n)))
  else
    if ((a.VBool? && b.VBool?) && op.Eq?) then
      Ok(VBool((a.b == b.b)))
    else
      Err(Fault.TypeError)
}

function evaluate(e: Expr, env: seq<Binding>): Result
  decreases e
{
  match e {
    case Num(i_e_n) =>
      Ok(VNum(i_e_n))
    case Bool(i_e_b) =>
      Ok(VBool(i_e_b))
    case Var(i_e_x) =>
      lookup(env, i_e_x)
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      var r1 := evaluate(i_e_rhs, env);
      match r1 {
        case Err(i_r1_why) =>
          r1
        case Ok(i_r1_v) =>
          evaluate(i_e_body, ([Binding(i_e_x, i_r1_v)] + env))
      }
    case Bin(i_e_op, i_e_l, i_e_r) =>
      var l := evaluate(i_e_l, env);
      match l {
        case Err(i_l_why) =>
          l
        case Ok(i_l_v) =>
          var r := evaluate(i_e_r, env);
          match r {
            case Err(i_r_why) =>
              r
            case Ok(i_r_v) =>
              applyOp(i_e_op, i_l_v, i_r_v)
          }
      }
    case If(i_e_cond, i_e_thn, i_e_els) =>
      var c := evaluate(i_e_cond, env);
      match c {
        case Err(i_c_why) =>
          c
        case Ok(i_c_v) =>
          if (!i_c_v.VBool?) then
            Err(Fault.TypeError)
          else
            if i_c_v.b then
              evaluate(i_e_thn, env)
            else
              evaluate(i_e_els, env)
      }
  }
}

function hasTy(v: Value, t: Ty): bool
{
  match v {
    case VNum(i_v_n) =>
      t.TInt?
    case VBool(i_v_b) =>
      t.TBool?
  }
}

function envMatches(env: seq<Binding>, tenv: seq<TBinding>): bool
  decreases env
{
  if (|env| == 0) then
    (|tenv| == 0)
  else
    if (|tenv| == 0) then
      false
    else
      (((env[0].x == tenv[0].x) && hasTy(env[0].v, tenv[0].t)) && envMatches(env[1..], tenv[1..]))
}

function lookupTy(tenv: seq<TBinding>, x: string): TyResult
  decreases tenv
{
  if (|tenv| == 0) then
    IllTyped(Fault.Unbound)
  else
    if (tenv[0].x == x) then
      Typed(tenv[0].t)
    else
      lookupTy(tenv[1..], x)
}

lemma lookupTy_ensures(tenv: seq<TBinding>, x: string)
  ensures forall env: Env :: (envMatches(env, tenv) ==> lookupTy(tenv, x).Typed? ==> (lookup(env, x).Ok? && hasTy(lookup(env, x).v, lookupTy(tenv, x).t)))
{
  forall env: Env | envMatches(env, tenv) && lookupTy(tenv, x).Typed?
    ensures lookup(env, x).Ok? && hasTy(lookup(env, x).v, lookupTy(tenv, x).t)
  {
    LookupSound(tenv, x, env);
  }
}

function opTy(op: Op, a: Ty, b: Ty): TyResult
{
  if (a.TInt? && b.TInt?) then
    if (op.Lt? || op.Eq?) then
      Typed(Ty.TBool)
    else
      Typed(Ty.TInt)
  else
    if ((a.TBool? && b.TBool?) && op.Eq?) then
      Typed(Ty.TBool)
    else
      IllTyped(Fault.TypeError)
}

function typeOf(e: Expr, tenv: seq<TBinding>): TyResult
  decreases e
{
  match e {
    case Num(i_e_n) =>
      Typed(Ty.TInt)
    case Bool(i_e_b) =>
      Typed(Ty.TBool)
    case Var(i_e_x) =>
      lookupTy(tenv, i_e_x)
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      var t1 := typeOf(i_e_rhs, tenv);
      match t1 {
        case IllTyped(i_t1_why) =>
          t1
        case Typed(i_t1_t) =>
          typeOf(i_e_body, ([TBinding(i_e_x, i_t1_t)] + tenv))
      }
    case Bin(i_e_op, i_e_l, i_e_r) =>
      var tl := typeOf(i_e_l, tenv);
      match tl {
        case IllTyped(i_tl_why) =>
          tl
        case Typed(i_tl_t) =>
          var tr := typeOf(i_e_r, tenv);
          match tr {
            case IllTyped(i_tr_why) =>
              tr
            case Typed(i_tr_t) =>
              opTy(i_e_op, i_tl_t, i_tr_t)
          }
      }
    case If(i_e_cond, i_e_thn, i_e_els) =>
      var tc := typeOf(i_e_cond, tenv);
      match tc {
        case IllTyped(i_tc_why) =>
          tc
        case Typed(i_tc_t) =>
          if (!i_tc_t.TBool?) then
            IllTyped(Fault.TypeError)
          else
            var tt := typeOf(i_e_thn, tenv);
            match tt {
              case IllTyped(i_tt_why) =>
                tt
              case Typed(i_tt_t) =>
                var te := typeOf(i_e_els, tenv);
                match te {
                  case IllTyped(i_te_why) =>
                    te
                  case Typed(i_te_t) =>
                    if (i_tt_t != i_te_t) then
                      IllTyped(Fault.TypeError)
                    else
                      tt
                }
            }
      }
  }
}

lemma typeOf_ensures(e: Expr, tenv: seq<TBinding>)
  ensures forall env: Env :: (envMatches(env, tenv) ==> typeOf(e, tenv).Typed? ==> evaluate(e, env).Ok? ==> hasTy(evaluate(e, env).v, typeOf(e, tenv).t))
  ensures forall env: Env :: (envMatches(env, tenv) ==> typeOf(e, tenv).Typed? ==> evaluate(e, env).Err? ==> evaluate(e, env).why.DivByZero?)
{
  // T1 — instantiate the explicit-environment lemma TypeSound (induction on e).
  forall env: Env | envMatches(env, tenv) && typeOf(e, tenv).Typed?
    ensures evaluate(e, env).Ok? ==> hasTy(evaluate(e, env).v, typeOf(e, tenv).t)
    ensures evaluate(e, env).Err? ==> evaluate(e, env).why.DivByZero?
  {
    TypeSound(e, tenv, env);
  }
}

function noDiv(e: Expr): bool
  decreases e
{
  match e {
    case Num(i_e_n) =>
      true
    case Bool(i_e_b) =>
      true
    case Var(i_e_x) =>
      true
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      (noDiv(i_e_rhs) && noDiv(i_e_body))
    case Bin(i_e_op, i_e_l, i_e_r) =>
      (((!i_e_op.Div?) && noDiv(i_e_l)) && noDiv(i_e_r))
    case If(i_e_cond, i_e_thn, i_e_els) =>
      ((noDiv(i_e_cond) && noDiv(i_e_thn)) && noDiv(i_e_els))
  }
}

function valueToExpr(v: Value): Expr
{
  match v {
    case VNum(i_v_n) =>
      Num(i_v_n)
    case VBool(i_v_b) =>
      Bool(i_v_b)
  }
}

function simplifyBin(op: Op, l: Expr, r: Expr): Expr
{
  if (l.Num? && r.Num?) then
    var folded := applyOp(op, VNum(l.n), VNum(r.n));
    match folded {
      case Ok(i_folded_v) =>
        valueToExpr(i_folded_v)
      case Err(i_folded_why) =>
        Bin(op, l, r)
    }
  else
    if ((l.Bool? && r.Bool?) && op.Eq?) then
      Bool((l.b == r.b))
    else
      if ((op.Add? && r.Num?) && (r.n == 0)) then
        l
      else
        if ((op.Add? && l.Num?) && (l.n == 0)) then
          r
        else
          if ((op.Sub? && r.Num?) && (r.n == 0)) then
            l
          else
            if ((op.Mul? && r.Num?) && (r.n == 1)) then
              l
            else
              if ((op.Mul? && l.Num?) && (l.n == 1)) then
                r
              else
                if ((op.Div? && r.Num?) && (r.n == 1)) then
                  l
                else
                  if (((op.Mul? && r.Num?) && (r.n == 0)) && noDiv(l)) then
                    Num(0)
                  else
                    if (((op.Mul? && l.Num?) && (l.n == 0)) && noDiv(r)) then
                      Num(0)
                    else
                      Bin(op, l, r)
}

lemma simplifyBin_ensures(op: Op, l: Expr, r: Expr)
  ensures (size(simplifyBin(op, l, r)) <= ((1 + size(l)) + size(r)))
  ensures forall tenv: TEnv :: (typeOf(Bin(op, l, r), tenv).Typed? ==> (typeOf(simplifyBin(op, l, r), tenv) == typeOf(Bin(op, l, r), tenv)))
  ensures forall tenv: TEnv, env: Env :: (typeOf(Bin(op, l, r), tenv).Typed? ==> envMatches(env, tenv) ==> (evaluate(simplifyBin(op, l, r), env) == evaluate(Bin(op, l, r), env)))
{
  SimplifyBinSize(op, l, r);
  forall tenv: TEnv | typeOf(Bin(op, l, r), tenv).Typed?
    ensures typeOf(simplifyBin(op, l, r), tenv) == typeOf(Bin(op, l, r), tenv)
  {
    SimplifyBinTy(op, l, r, tenv);
  }
  forall tenv: TEnv, env: Env | typeOf(Bin(op, l, r), tenv).Typed? && envMatches(env, tenv)
    ensures evaluate(simplifyBin(op, l, r), env) == evaluate(Bin(op, l, r), env)
  {
    SimplifyBinSem(op, l, r, tenv, env);
  }
}

function simplifyIf(c: Expr, t: Expr, e: Expr): Expr
{
  match c {
    case Bool(i_c_b) =>
      if i_c_b then
        t
      else
        e
    case _ =>
      If(c, t, e)
  }
}

lemma simplifyIf_ensures(c: Expr, t: Expr, e: Expr)
  ensures (size(simplifyIf(c, t, e)) <= (((1 + size(c)) + size(t)) + size(e)))
  ensures forall tenv: TEnv :: (typeOf(If(c, t, e), tenv).Typed? ==> (typeOf(simplifyIf(c, t, e), tenv) == typeOf(If(c, t, e), tenv)))
  ensures forall tenv: TEnv, env: Env :: (typeOf(If(c, t, e), tenv).Typed? ==> envMatches(env, tenv) ==> (evaluate(simplifyIf(c, t, e), env) == evaluate(If(c, t, e), env)))
{
  SimplifyIfSize(c, t, e);
  forall tenv: TEnv | typeOf(If(c, t, e), tenv).Typed?
    ensures typeOf(simplifyIf(c, t, e), tenv) == typeOf(If(c, t, e), tenv)
  {
    SimplifyIfTy(c, t, e, tenv);
  }
  forall tenv: TEnv, env: Env | typeOf(If(c, t, e), tenv).Typed? && envMatches(env, tenv)
    ensures evaluate(simplifyIf(c, t, e), env) == evaluate(If(c, t, e), env)
  {
    SimplifyIfSem(c, t, e, tenv, env);
  }
}

function optimize(e: Expr): Expr
  decreases e
{
  match e {
    case Num(i_e_n) =>
      e
    case Bool(i_e_b) =>
      e
    case Var(i_e_x) =>
      e
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      Let(i_e_x, optimize(i_e_rhs), optimize(i_e_body))
    case Bin(i_e_op, i_e_l, i_e_r) =>
      simplifyBin(i_e_op, optimize(i_e_l), optimize(i_e_r))
    case If(i_e_cond, i_e_thn, i_e_els) =>
      simplifyIf(optimize(i_e_cond), optimize(i_e_thn), optimize(i_e_els))
  }
}

lemma optimize_ensures(e: Expr)
  ensures (size(optimize(e)) <= size(e))
  ensures forall tenv: TEnv :: (typeOf(e, tenv).Typed? ==> (typeOf(optimize(e), tenv) == typeOf(e, tenv)))
  ensures forall tenv: TEnv, env: Env :: (typeOf(e, tenv).Typed? ==> envMatches(env, tenv) ==> (evaluate(optimize(e), env) == evaluate(e, env)))
{
  // T2 — size, type preservation, semantic preservation (each by induction on e).
  OptimizeSize(e);
  forall tenv: TEnv | typeOf(e, tenv).Typed?
    ensures typeOf(optimize(e), tenv) == typeOf(e, tenv)
  {
    OptimizeTy(e, tenv);
  }
  forall tenv: TEnv, env: Env | typeOf(e, tenv).Typed? && envMatches(env, tenv)
    ensures evaluate(optimize(e), env) == evaluate(e, env)
  {
    OptimizeSem(e, tenv, env);
  }
}

function naiveBin(op: Op, l: Expr, r: Expr): Expr
{
  if (l.Num? && r.Num?) then
    var folded := applyOp(op, VNum(l.n), VNum(r.n));
    match folded {
      case Ok(i_folded_v) =>
        valueToExpr(i_folded_v)
      case Err(i_folded_why) =>
        Bin(op, l, r)
    }
  else
    if ((op.Add? && r.Num?) && (r.n == 0)) then
      l
    else
      if ((op.Add? && l.Num?) && (l.n == 0)) then
        r
      else
        if ((op.Sub? && r.Num?) && (r.n == 0)) then
          l
        else
          if ((op.Mul? && r.Num?) && (r.n == 1)) then
            l
          else
            if ((op.Mul? && l.Num?) && (l.n == 1)) then
              r
            else
              if ((op.Div? && r.Num?) && (r.n == 1)) then
                l
              else
                if ((op.Mul? && r.Num?) && (r.n == 0)) then
                  Num(0)
                else
                  if ((op.Mul? && l.Num?) && (l.n == 0)) then
                    Num(0)
                  else
                    Bin(op, l, r)
}

function optimizeNaive(e: Expr): Expr
  decreases e
{
  match e {
    case Num(i_e_n) =>
      e
    case Bool(i_e_b) =>
      e
    case Var(i_e_x) =>
      e
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      Let(i_e_x, optimizeNaive(i_e_rhs), optimizeNaive(i_e_body))
    case Bin(i_e_op, i_e_l, i_e_r) =>
      naiveBin(i_e_op, optimizeNaive(i_e_l), optimizeNaive(i_e_r))
    case If(i_e_cond, i_e_thn, i_e_els) =>
      simplifyIf(optimizeNaive(i_e_cond), optimizeNaive(i_e_thn), optimizeNaive(i_e_els))
  }
}

lemma optimizeNaive_ensures(e: Expr)
  ensures (size(optimizeNaive(e)) <= size(e))
{
  OptimizeNaiveSize(e);
}

function halt(stack: seq<Value>, env: seq<Binding>): Outcome
{
  Halt(stack, env)
}

function crash(why: Fault): Outcome
{
  Crash(why)
}

function pushed(v: Value, stack: seq<Value>): seq<Value>
{
  ([v] + stack)
}

function run(code: seq<Instr>, stack: seq<Value>, env: seq<Binding>): Outcome
  decreases code
{
  if (|code| == 0) then
    halt(stack, env)
  else
    var ins := code[0];
    var rest := code[1..];
    match ins {
      case Push(i_ins_v) =>
        run(rest, ([i_ins_v] + stack), env)
      case Prim(i_ins_op) =>
        if (|stack| < 2) then
          crash(Fault.Underflow)
        else
          var b := stack[0];
          var a := stack[1];
          var res := applyOp(i_ins_op, a, b);
          match res {
            case Err(i_res_why) =>
              crash(i_res_why)
            case Ok(i_res_v) =>
              run(rest, ([i_res_v] + stack[2..]), env)
          }
      case Load(i_ins_x) =>
        var res := lookup(env, i_ins_x);
        match res {
          case Err(i_res_why) =>
            crash(i_res_why)
          case Ok(i_res_v) =>
            run(rest, ([i_res_v] + stack), env)
        }
      case Bind(i_ins_x) =>
        if (|stack| < 1) then
          crash(Fault.Underflow)
        else
          run(rest, stack[1..], ([Binding(i_ins_x, stack[0])] + env))
      case Unbind =>
        if (|env| < 1) then
          crash(Fault.Underflow)
        else
          run(rest, stack, env[1..])
      case Branch(i_ins_thn, i_ins_els) =>
        if (|stack| < 1) then
          crash(Fault.Underflow)
        else
          var c := stack[0];
          match c {
            case VBool(i_c_b) =>
              var inner := run((if i_c_b then i_ins_thn else i_ins_els), stack[1..], env);
              match inner {
                case Crash(i_inner_why) =>
                  inner
                case Halt(i_inner_stack, i_inner_env) =>
                  run(rest, i_inner_stack, i_inner_env)
              }
            case VNum(i_c_n) =>
              crash(Fault.TypeError)
          }
    }
}

function compile(e: Expr): seq<Instr>
  decreases e
{
  match e {
    case Num(i_e_n) =>
      [Push(VNum(i_e_n))]
    case Bool(i_e_b) =>
      [Push(VBool(i_e_b))]
    case Var(i_e_x) =>
      [Load(i_e_x)]
    case Let(i_e_x, i_e_rhs, i_e_body) =>
      (((compile(i_e_rhs) + [Bind(i_e_x)]) + compile(i_e_body)) + [Instr.Unbind])
    case Bin(i_e_op, i_e_l, i_e_r) =>
      ((compile(i_e_l) + compile(i_e_r)) + [Prim(i_e_op)])
    case If(i_e_cond, i_e_thn, i_e_els) =>
      (compile(i_e_cond) + [Branch(compile(i_e_thn), compile(i_e_els))])
  }
}

lemma compile_ensures(e: Expr)
  ensures forall env: Env, stack: Stack :: (evaluate(e, env).Ok? ==> (run(compile(e), stack, env) == halt(pushed(evaluate(e, env).v, stack), env)))
  ensures forall env: Env, stack: Stack :: (evaluate(e, env).Err? ==> (run(compile(e), stack, env) == crash(evaluate(e, env).why)))
{
  // T3 — instantiate CompileCorrect (induction on e, with RunAppend for code concatenation).
  forall env: Env, stack: Stack
    ensures evaluate(e, env).Ok? ==> run(compile(e), stack, env) == halt(pushed(evaluate(e, env).v, stack), env)
    ensures evaluate(e, env).Err? ==> run(compile(e), stack, env) == crash(evaluate(e, env).why)
  {
    CompileCorrect(e, stack, env);
  }
}

function runPipeline(e: Expr): Result
{
  var t := typeOf(e, []);
  match t {
    case IllTyped(i_t_why) =>
      Err(i_t_why)
    case Typed(i_t_t) =>
      var out := run(compile(optimize(e)), [], []);
      match out {
        case Crash(i_out_why) =>
          Err(i_out_why)
        case Halt(i_out_stack, i_out_env) =>
          if (|i_out_stack| != 1) then
            Err(Fault.Underflow)
          else
            Ok(i_out_stack[0])
      }
  }
}

lemma runPipeline_ensures(e: Expr)
  ensures (typeOf(e, []).Typed? ==> (runPipeline(e) == evaluate(e, [])))
{
  // T4 — compose T2 (at the empty environments) with T3 on the optimized program.
  if typeOf(e, []).Typed? {
    OptimizeSem(e, [], []);
    CompileCorrect(optimize(e), [], []);
  }
}


// ═══════════════════════════════════════════════════════════════════════
// Hand-written proofs. Everything above this line is generated from
// core.ts by LemmaScript and is never edited; everything below is an
// addition (lsc check enforces the additions-only discipline).
// ═══════════════════════════════════════════════════════════════════════

// ───────────────────────── T1: type soundness ─────────────────────────

// A primitive applied to well-typed operands either returns a value of
// the predicted type or divides by zero. It never raises TypeError.
lemma ApplyOpTyped(op: Op, a: Value, b: Value, ta: Ty, tb: Ty)
  requires hasTy(a, ta) && hasTy(b, tb)
  requires opTy(op, ta, tb).Typed?
  ensures applyOp(op, a, b).Ok? ==> hasTy(applyOp(op, a, b).v, opTy(op, ta, tb).t)
  ensures applyOp(op, a, b).Err? ==> applyOp(op, a, b).why.DivByZero?
{
}

// If the typing environment knows x at type t, the matching run-time
// environment holds a value of type t for x. Induction on the environment.
lemma LookupSound(tenv: TEnv, x: string, env: Env)
  requires envMatches(env, tenv)
  requires lookupTy(tenv, x).Typed?
  ensures lookup(env, x).Ok? && hasTy(lookup(env, x).v, lookupTy(tenv, x).t)
  decreases tenv
{
  if |tenv| == 0 {
  } else if tenv[0].x == x {
  } else {
    LookupSound(tenv[1..], x, env[1..]);
  }
}

// Extending matching environments with a matching binding keeps them matching.
lemma EnvMatchesExtend(env: Env, tenv: TEnv, x: string, v: Value, t: Ty)
  requires envMatches(env, tenv)
  requires hasTy(v, t)
  ensures envMatches([Binding(x, v)] + env, [TBinding(x, t)] + tenv)
{
  var env2 := [Binding(x, v)] + env;
  var tenv2 := [TBinding(x, t)] + tenv;
  assert env2[1..] == env;
  assert tenv2[1..] == tenv;
}

// T1 with the environment made explicit. Structural induction on e.
// The Let case is the interesting one: the body is checked in an
// extended typing environment, so we run it in the correspondingly
// extended run-time environment, which EnvMatchesExtend says still matches.
lemma TypeSound(e: Expr, tenv: TEnv, env: Env)
  requires envMatches(env, tenv)
  requires typeOf(e, tenv).Typed?
  ensures evaluate(e, env).Ok? ==> hasTy(evaluate(e, env).v, typeOf(e, tenv).t)
  ensures evaluate(e, env).Err? ==> evaluate(e, env).why.DivByZero?
  decreases e
{
  match e {
    case Num(_) =>
    case Bool(_) =>
    case Var(x) =>
      LookupSound(tenv, x, env);
    case Let(x, rhs, body) =>
      TypeSound(rhs, tenv, env);
      var t1 := typeOf(rhs, tenv);
      var r1 := evaluate(rhs, env);
      if r1.Ok? {
        EnvMatchesExtend(env, tenv, x, r1.v, t1.t);
        TypeSound(body, [TBinding(x, t1.t)] + tenv, [Binding(x, r1.v)] + env);
      }
    case Bin(op, l, r) =>
      TypeSound(l, tenv, env);
      var lv := evaluate(l, env);
      if lv.Ok? {
        TypeSound(r, tenv, env);
        var rv := evaluate(r, env);
        if rv.Ok? {
          ApplyOpTyped(op, lv.v, rv.v, typeOf(l, tenv).t, typeOf(r, tenv).t);
        }
      }
    case If(c, t, el) =>
      TypeSound(c, tenv, env);
      var cv := evaluate(c, env);
      if cv.Ok? {
        TypeSound(t, tenv, env);
        TypeSound(el, tenv, env);
      }
  }
}

// ───────────── Totality: well-typed + division-free ⇒ a value ─────────────
//
// This is the side condition that licenses deleting a subexpression
// (x * 0 → 0). T1 leaves exactly one possible fault, DivByZero, and a
// division-free expression cannot raise it.
lemma NoDivTotal(e: Expr, tenv: TEnv, env: Env)
  requires envMatches(env, tenv)
  requires typeOf(e, tenv).Typed?
  requires noDiv(e)
  ensures evaluate(e, env).Ok?
  decreases e
{
  match e {
    case Num(_) =>
    case Bool(_) =>
    case Var(x) =>
      LookupSound(tenv, x, env);
    case Let(x, rhs, body) =>
      NoDivTotal(rhs, tenv, env);
      TypeSound(rhs, tenv, env);
      var t1 := typeOf(rhs, tenv);
      var r1 := evaluate(rhs, env);
      EnvMatchesExtend(env, tenv, x, r1.v, t1.t);
      NoDivTotal(body, [TBinding(x, t1.t)] + tenv, [Binding(x, r1.v)] + env);
    case Bin(op, l, r) =>
      NoDivTotal(l, tenv, env);
      NoDivTotal(r, tenv, env);
      TypeSound(l, tenv, env);
      TypeSound(r, tenv, env);
    case If(c, t, el) =>
      NoDivTotal(c, tenv, env);
      TypeSound(c, tenv, env);
      NoDivTotal(t, tenv, env);
      NoDivTotal(el, tenv, env);
  }
}

// ───────────────────────── T2: the optimizer ─────────────────────────

lemma FloorDivOne(n: int)
  ensures JSFloorDiv(n, 1) == n
{
}

lemma SimplifyBinSize(op: Op, l: Expr, r: Expr)
  ensures size(simplifyBin(op, l, r)) <= 1 + size(l) + size(r)
{
  size_ensures(l);
  size_ensures(r);
}

lemma SimplifyBinTy(op: Op, l: Expr, r: Expr, tenv: TEnv)
  requires typeOf(Bin(op, l, r), tenv).Typed?
  ensures typeOf(simplifyBin(op, l, r), tenv) == typeOf(Bin(op, l, r), tenv)
{
}

// Each rewrite rule, justified:
//   folding      — the literal IS the value the primitive computes;
//   identities   — T1 makes the surviving operand an integer (or a
//                  DivByZero, which both sides then raise);
//   annihilation — NoDivTotal makes the deleted operand a value, so
//                  deleting it loses no fault.
lemma SimplifyBinSem(op: Op, l: Expr, r: Expr, tenv: TEnv, env: Env)
  requires typeOf(Bin(op, l, r), tenv).Typed?
  requires envMatches(env, tenv)
  ensures evaluate(simplifyBin(op, l, r), env) == evaluate(Bin(op, l, r), env)
{
  TypeSound(l, tenv, env);
  TypeSound(r, tenv, env);
  if noDiv(l) {
    NoDivTotal(l, tenv, env);
  }
  if noDiv(r) {
    NoDivTotal(r, tenv, env);
  }
  var lv := evaluate(l, env);
  if lv.Ok? && lv.v.VNum? {
    FloorDivOne(lv.v.n);
  }
}

lemma SimplifyIfSize(c: Expr, t: Expr, e: Expr)
  ensures size(simplifyIf(c, t, e)) <= 1 + size(c) + size(t) + size(e)
{
  size_ensures(c);
  size_ensures(t);
  size_ensures(e);
}

lemma SimplifyIfTy(c: Expr, t: Expr, e: Expr, tenv: TEnv)
  requires typeOf(If(c, t, e), tenv).Typed?
  ensures typeOf(simplifyIf(c, t, e), tenv) == typeOf(If(c, t, e), tenv)
{
}

lemma SimplifyIfSem(c: Expr, t: Expr, e: Expr, tenv: TEnv, env: Env)
  requires typeOf(If(c, t, e), tenv).Typed?
  requires envMatches(env, tenv)
  ensures evaluate(simplifyIf(c, t, e), env) == evaluate(If(c, t, e), env)
{
}

lemma OptimizeSize(e: Expr)
  ensures size(optimize(e)) <= size(e)
  decreases e
{
  match e {
    case Num(_) =>
    case Bool(_) =>
    case Var(_) =>
    case Let(x, rhs, body) =>
      OptimizeSize(rhs);
      OptimizeSize(body);
    case Bin(op, l, r) =>
      OptimizeSize(l);
      OptimizeSize(r);
      SimplifyBinSize(op, optimize(l), optimize(r));
    case If(c, t, el) =>
      OptimizeSize(c);
      OptimizeSize(t);
      OptimizeSize(el);
      SimplifyIfSize(optimize(c), optimize(t), optimize(el));
  }
}

lemma OptimizeTy(e: Expr, tenv: TEnv)
  requires typeOf(e, tenv).Typed?
  ensures typeOf(optimize(e), tenv) == typeOf(e, tenv)
  decreases e
{
  match e {
    case Num(_) =>
    case Bool(_) =>
    case Var(_) =>
    case Let(x, rhs, body) =>
      OptimizeTy(rhs, tenv);
      var t1 := typeOf(rhs, tenv);
      OptimizeTy(body, [TBinding(x, t1.t)] + tenv);
    case Bin(op, l, r) =>
      OptimizeTy(l, tenv);
      OptimizeTy(r, tenv);
      assert typeOf(Bin(op, optimize(l), optimize(r)), tenv) == typeOf(Bin(op, l, r), tenv);
      SimplifyBinTy(op, optimize(l), optimize(r), tenv);
    case If(c, t, el) =>
      OptimizeTy(c, tenv);
      OptimizeTy(t, tenv);
      OptimizeTy(el, tenv);
      assert typeOf(If(optimize(c), optimize(t), optimize(el)), tenv) == typeOf(If(c, t, el), tenv);
      SimplifyIfTy(optimize(c), optimize(t), optimize(el), tenv);
  }
}

// T2 with the environments made explicit. Structural induction on e;
// the children are optimized first (bottom-up), so the inductive
// hypothesis rewrites them in place and the local rule lemma finishes.
lemma OptimizeSem(e: Expr, tenv: TEnv, env: Env)
  requires typeOf(e, tenv).Typed?
  requires envMatches(env, tenv)
  ensures evaluate(optimize(e), env) == evaluate(e, env)
  decreases e
{
  match e {
    case Num(_) =>
    case Bool(_) =>
    case Var(_) =>
    case Let(x, rhs, body) =>
      OptimizeSem(rhs, tenv, env);
      TypeSound(rhs, tenv, env);
      var t1 := typeOf(rhs, tenv);
      var r1 := evaluate(rhs, env);
      if r1.Ok? {
        EnvMatchesExtend(env, tenv, x, r1.v, t1.t);
        OptimizeSem(body, [TBinding(x, t1.t)] + tenv, [Binding(x, r1.v)] + env);
      }
    case Bin(op, l, r) =>
      OptimizeSem(l, tenv, env);
      OptimizeSem(r, tenv, env);
      OptimizeTy(l, tenv);
      OptimizeTy(r, tenv);
      var ol := optimize(l);
      var orr := optimize(r);
      assert typeOf(Bin(op, ol, orr), tenv) == typeOf(Bin(op, l, r), tenv);
      assert evaluate(Bin(op, ol, orr), env) == evaluate(Bin(op, l, r), env);
      SimplifyBinSem(op, ol, orr, tenv, env);
    case If(c, t, el) =>
      OptimizeSem(c, tenv, env);
      OptimizeSem(t, tenv, env);
      OptimizeSem(el, tenv, env);
      OptimizeTy(c, tenv);
      OptimizeTy(t, tenv);
      OptimizeTy(el, tenv);
      var oc := optimize(c);
      var ot := optimize(t);
      var oe := optimize(el);
      assert typeOf(If(oc, ot, oe), tenv) == typeOf(If(c, t, el), tenv);
      assert evaluate(If(oc, ot, oe), env) == evaluate(If(c, t, el), env);
      SimplifyIfSem(oc, ot, oe, tenv, env);
  }
}

// The naive optimizer at least never grows a program.
lemma NaiveBinSize(op: Op, l: Expr, r: Expr)
  ensures size(naiveBin(op, l, r)) <= 1 + size(l) + size(r)
{
  size_ensures(l);
  size_ensures(r);
}

lemma OptimizeNaiveSize(e: Expr)
  ensures size(optimizeNaive(e)) <= size(e)
  decreases e
{
  match e {
    case Num(_) =>
    case Bool(_) =>
    case Var(_) =>
    case Let(x, rhs, body) =>
      OptimizeNaiveSize(rhs);
      OptimizeNaiveSize(body);
    case Bin(op, l, r) =>
      OptimizeNaiveSize(l);
      OptimizeNaiveSize(r);
      NaiveBinSize(op, optimizeNaive(l), optimizeNaive(r));
    case If(c, t, el) =>
      OptimizeNaiveSize(c);
      OptimizeNaiveSize(t);
      OptimizeNaiveSize(el);
      SimplifyIfSize(optimizeNaive(c), optimizeNaive(t), optimizeNaive(el));
  }
}

// ─────────────── The counterexamples: why the rules need guards ───────────────

// (1 / 0) * 0 is well-typed and means "crash". The naive optimizer turns
// it into 0. The verified optimizer leaves it alone, as T2 requires.
lemma NaiveMulZero()
  ensures var e := Bin(Mul, Bin(Div, Num(1), Num(0)), Num(0));
    typeOf(e, []) == Typed(TInt)
    && evaluate(e, []) == Err(DivByZero)
    && evaluate(optimizeNaive(e), []) == Ok(VNum(0))
    && optimize(e) == e
{
  var inner := Bin(Div, Num(1), Num(0));
  var e := Bin(Mul, inner, Num(0));
  assert evaluate(inner, []) == Err(DivByZero);
  assert evaluate(e, []) == Err(DivByZero);
  assert optimizeNaive(inner) == inner;
  assert optimizeNaive(e) == Num(0);
  assert optimize(inner) == inner;
  assert !noDiv(inner);
  assert optimize(e) == e;
}

// The exact statement T2 makes about `optimize` is FALSE of `optimizeNaive`:
// there is a well-typed program whose meaning it changes.
lemma NaiveRefutesT2()
  ensures exists e: Expr :: typeOf(e, []).Typed? && evaluate(optimizeNaive(e), []) != evaluate(e, [])
{
  NaiveMulZero();
  var e := Bin(Mul, Bin(Div, Num(1), Num(0)), Num(0));
  assert typeOf(e, []).Typed? && evaluate(optimizeNaive(e), []) != evaluate(e, []);
}

// `true + 0` means TypeError, but x + 0 → x turns it into `true`. This is
// why T2 is stated for WELL-TYPED programs only: without the typing
// hypothesis even the identity rules are unsound — for the naive and the
// verified optimizer alike. The type checker rejects this program, so the
// pipeline (T4) never runs it.
lemma IdentityNeedsTypes()
  ensures var e := Bin(Add, Bool(true), Num(0));
    typeOf(e, []).IllTyped?
    && evaluate(e, []) == Err(TypeError)
    && evaluate(optimizeNaive(e), []) == Ok(VBool(true))
    && evaluate(optimize(e), []) == Ok(VBool(true))
{
  var e := Bin(Add, Bool(true), Num(0));
  assert evaluate(e, []) == Err(TypeError);
  assert optimizeNaive(e) == Bool(true);
  assert optimize(e) == Bool(true);
}

// ───────────────────── T3: the compiler and the machine ─────────────────────

// Running concatenated code is running the first block, then — if it
// halted — running the second from where the first left off. Induction
// on the first block; this is the glue for every compile case.
lemma RunAppend(c1: seq<Instr>, c2: seq<Instr>, stack: Stack, env: Env)
  ensures run(c1, stack, env).Crash? ==> run(c1 + c2, stack, env) == run(c1, stack, env)
  ensures run(c1, stack, env).Halt? ==> run(c1 + c2, stack, env) == run(c2, run(c1, stack, env).stack, run(c1, stack, env).env)
  decreases c1
{
  if |c1| == 0 {
    assert c1 + c2 == c2;
  } else {
    var ins := c1[0];
    var rest := c1[1..];
    assert (c1 + c2)[0] == ins;
    assert (c1 + c2)[1..] == rest + c2;
    match ins {
      case Push(v) =>
        RunAppend(rest, c2, [v] + stack, env);
      case Prim(op) =>
        if |stack| >= 2 {
          var res := applyOp(op, stack[1], stack[0]);
          if res.Ok? {
            RunAppend(rest, c2, [res.v] + stack[2..], env);
          }
        }
      case Load(x) =>
        var res := lookup(env, x);
        if res.Ok? {
          RunAppend(rest, c2, [res.v] + stack, env);
        }
      case Bind(x) =>
        if |stack| >= 1 {
          RunAppend(rest, c2, stack[1..], [Binding(x, stack[0])] + env);
        }
      case Unbind =>
        if |env| >= 1 {
          RunAppend(rest, c2, stack, env[1..]);
        }
      case Branch(thn, els) =>
        if |stack| >= 1 && stack[0].VBool? {
          var inner := run(if stack[0].b then thn else els, stack[1..], env);
          if inner.Halt? {
            RunAppend(rest, c2, inner.stack, inner.env);
          }
        }
    }
  }
}

// T3 with stack and environment made explicit. Structural induction on e.
// Every case: split the generated code into its blocks with RunAppend,
// use the inductive hypothesis on each sub-program, and step the single
// instruction that combines their results.
lemma CompileCorrect(e: Expr, stack: Stack, env: Env)
  ensures evaluate(e, env).Ok? ==> run(compile(e), stack, env) == Halt([evaluate(e, env).v] + stack, env)
  ensures evaluate(e, env).Err? ==> run(compile(e), stack, env) == Crash(evaluate(e, env).why)
  decreases e
{
  match e {
    case Num(n) =>
      assert run(compile(e), stack, env) == run([], [VNum(n)] + stack, env);
    case Bool(b) =>
      assert run(compile(e), stack, env) == run([], [VBool(b)] + stack, env);
    case Var(x) =>
      var res := lookup(env, x);
      if res.Ok? {
        assert run(compile(e), stack, env) == run([], [res.v] + stack, env);
      }
    case Let(x, rhs, body) =>
      var c1 := compile(rhs);
      var c2 := [Bind(x)];
      var c3 := compile(body);
      var c4 := [Instr.Unbind];
      assert compile(e) == c1 + (c2 + (c3 + c4));
      CompileCorrect(rhs, stack, env);
      RunAppend(c1, c2 + (c3 + c4), stack, env);
      var r1 := evaluate(rhs, env);
      if r1.Ok? {
        var stack1 := [r1.v] + stack;
        var env2 := [Binding(x, r1.v)] + env;
        assert run(c2, stack1, env) == run([], stack, env2);
        RunAppend(c2, c3 + c4, stack1, env);
        CompileCorrect(body, stack, env2);
        RunAppend(c3, c4, stack, env2);
        var r2 := evaluate(body, env2);
        if r2.Ok? {
          assert env2[1..] == env;
          assert run(c4, [r2.v] + stack, env2) == run([], [r2.v] + stack, env);
        }
      }
    case Bin(op, l, r) =>
      var cl := compile(l);
      var cr := compile(r);
      assert compile(e) == (cl + cr) + [Prim(op)];
      CompileCorrect(l, stack, env);
      RunAppend(cl, cr, stack, env);
      RunAppend(cl + cr, [Prim(op)], stack, env);
      var lv := evaluate(l, env);
      if lv.Ok? {
        CompileCorrect(r, [lv.v] + stack, env);
        var rv := evaluate(r, env);
        if rv.Ok? {
          var st := [rv.v] + ([lv.v] + stack);
          assert st[0] == rv.v && st[1] == lv.v && st[2..] == stack;
          var res := applyOp(op, lv.v, rv.v);
          if res.Ok? {
            assert run([Prim(op)], st, env) == run([], [res.v] + stack, env);
          }
        }
      }
    case If(c, t, el) =>
      var cc := compile(c);
      var br := [Branch(compile(t), compile(el))];
      assert compile(e) == cc + br;
      CompileCorrect(c, stack, env);
      RunAppend(cc, br, stack, env);
      var cv := evaluate(c, env);
      if cv.Ok? && cv.v.VBool? {
        var st := [cv.v] + stack;
        assert st[1..] == stack;
        CompileCorrect(t, stack, env);
        CompileCorrect(el, stack, env);
        var inner := run(if cv.v.b then compile(t) else compile(el), stack, env);
        if inner.Halt? {
          assert run(br, st, env) == run([], inner.stack, inner.env);
        }
      }
  }
}
